### ISSUE TITLE
Error arise during testing

### ISSUE THREAD

**Issue by Vishal2188** [waleedgondal/Texture-based-Super-Resolution-Network#1]
File "test.py", line 59, in <module>
    sr_net.load_state_dict(torch.load(opt.path_model, map_location=lambda storage, loc: storage))
  File "/home/dl/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 742, in load_state_dict
    state_dict = state_dict.copy()
  File "/home/dl/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
**AttributeError: 'Model_4x' object has no attribute 'copy'**

**Comment by waleedgondal** [comment]
Hi Vishal, I couldn't reproduce the error on either CPU or GPU. It seems to be a pytorch's version related issue. Could you please tell me your pytorch version? 

Update: I have however updated the code according to the latest pytorch version.

**Comment by Vishal2188** [comment]
Thank you for your reply...

I have checked the pytorch version... it is lower version.... I have
upgrade it and now I can run it...

Thanks a lot.

**Comment by waleedgondal** [comment]
No problem!
